import { StyleSheet } from 'react-native';

import { palette } from '@/shared/design-system/tokens';

export const styles = StyleSheet.create({
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  missing: {
    color: palette.ink,
    fontWeight: '800',
  },
  readerHeader: {
    minHeight: 72,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerText: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '900',
  },
  headerMeta: {
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  content: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 120,
  },
  chapterTitle: {
    fontSize: 30,
    lineHeight: 38,
    fontWeight: '900',
    marginBottom: 22,
  },
  body: {
    fontFamily: 'serif',
    padding: 0,
    textAlignVertical: 'top',
  },
  selectionHint: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
    marginBottom: 14,
  },
  narrationPosition: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '900',
    marginBottom: 10,
  },
  player: {
    minHeight: 82,
    borderTopWidth: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
  },
  navButton: {
    minWidth: 44,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  playButton: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
  },
  disabled: {
    opacity: 0.3,
  },
  brightnessOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  drawerRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  drawerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.12)',
  },
  drawerPanel: {
    width: '100%',
    maxHeight: '66%',
    backgroundColor: '#F1F0F6',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    overflow: 'hidden',
  },
  drawerContent: {
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 28,
    gap: 12,
  },
  drawerHeader: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  drawerTitle: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: '900',
  },
  drawerCloseButton: {
    position: 'absolute',
    right: 0,
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#DDDCE4',
  },
  drawerCloseText: {
    color: palette.umber,
    fontSize: 20,
    fontWeight: '900',
  },
  drawerQuickControls: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 40,
  },
  drawerPillControl: {
    flex: 1,
    minHeight: 44,
    flexDirection: 'row',
    borderRadius: 16,
    backgroundColor: '#DDDCE4',
    overflow: 'hidden',
  },
  drawerPillButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  drawerPillText: {
    color: palette.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  drawerPillTextLarge: {
    color: palette.ink,
    fontSize: 21,
    fontWeight: '900',
  },
  drawerThemeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  drawerThemeCard: {
    width: '30.6%',
    minHeight: 66,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
    gap: 2,
  },
  drawerThemeCardActive: {
    borderColor: palette.ink,
  },
  drawerThemeAa: {
    fontSize: 22,
    fontWeight: '900',
  },
  drawerThemeLabel: {
    fontSize: 11,
    fontWeight: '800',
  },
  drawerSection: {
    gap: 8,
  },
  drawerLabel: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  drawerSegment: {
    flexDirection: 'row',
    gap: 6,
    padding: 4,
    borderRadius: 8,
    backgroundColor: '#DDDCE4',
  },
  drawerSegmentButton: {
    flex: 1,
    minHeight: 40,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  drawerSegmentText: {
    color: palette.umber,
    fontWeight: '900',
  },
  drawerSegmentTextActive: {
    color: palette.panel,
  },
  drawerStepper: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DDDCE4',
    backgroundColor: '#FAFAFC',
    padding: 6,
  },
  drawerStepButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E4E3EA',
  },
  drawerStepText: {
    color: palette.umber,
    fontSize: 24,
    fontWeight: '900',
  },
  drawerStepValue: {
    color: palette.ink,
    fontSize: 18,
    fontWeight: '900',
  },
  drawerVoiceList: {
    gap: 8,
  },
  drawerVoiceOption: {
    minHeight: 42,
    justifyContent: 'center',
    borderRadius: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#DDDCE4',
    backgroundColor: '#FAFAFC',
  },
  drawerVoiceOptionActive: {
    backgroundColor: palette.umber,
    borderColor: palette.umber,
  },
  drawerVoiceText: {
    color: palette.umber,
    fontWeight: '800',
  },
  drawerVoiceTextActive: {
    color: palette.panel,
  },
  drawerRateGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  drawerRateOption: {
    minWidth: 64,
    minHeight: 38,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  drawerRateText: {
    fontSize: 13,
    fontWeight: '900',
  },
  drawerDoneButton: {
    minHeight: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#DDDCE4',
  },
  drawerDoneText: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: '900',
  },
});
